### ISSUE TITLE
Throw error for non-existent named breakpoints

### ISSUE THREAD

**Issue by andreekeberg** [pocketsize/bolts-lib#14]
If you try to use a named breakpoint in width, width-from, width-to (or any other breakpoint function) that does not exist, it is currently simply printed in the CSS output, and in the width-from/height-from functions, `1` is appended to the string instead of the intended behavior (which is incrementing the breakpoint by one unit).

In this scenario, an `@error` or `@warning` should probably be thrown.

**Comment by djurnamn** [comment]
Fixed in #18
